/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.edusys.ui;

import com.edusys.DAO.StaffDAO;
import com.edusys.entity.Staff;
import com.edusys.utils.Auth;
import com.edusys.utils.MsgBox;
import com.edusys.utils.Xmail;
import java.awt.Color;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.geom.RoundRectangle2D;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Sang
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    StaffDAO dao = new StaffDAO();
    public Login() {
        setUndecorated(true);
        initComponents();
        prepareUI();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLogin = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        lblDetail = new javax.swing.JLabel();
        lblAccIcon = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassicon = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        chkPassword = new javax.swing.JCheckBox();
        lblForgot = new javax.swing.JLabel();
        lblLine = new javax.swing.JLabel();
        btnLogin = new javax.swing.JPanel();
        lblLogin1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSignUp = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pnlSignup = new javax.swing.JPanel();
        lblnameIcon = new javax.swing.JLabel();
        lblEmailIcon = new javax.swing.JLabel();
        lblWelcome1 = new javax.swing.JLabel();
        lblDetail2 = new javax.swing.JLabel();
        lblAccIconSignUp = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPassiconSignUp = new javax.swing.JLabel();
        txtPasswordSignUp = new javax.swing.JPasswordField();
        chkPasswordSignUp = new javax.swing.JCheckBox();
        btnSignUp = new javax.swing.JPanel();
        lblLogin2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSignIn = new javax.swing.JLabel();
        lblConfirm = new javax.swing.JLabel();
        txtConfirm = new javax.swing.JPasswordField();
        txtUserSignUp1 = new javax.swing.JTextField();
        cboRole = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        pnlLogo = new javax.swing.JPanel();
        lblEdusys = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblDecription = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        pnlForgot = new javax.swing.JPanel();
        lblWelcome2 = new javax.swing.JLabel();
        lblDetail3 = new javax.swing.JLabel();
        btnChangePasswordFG = new javax.swing.JPanel();
        lblLogin3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSignIn1 = new javax.swing.JLabel();
        lblDetail4 = new javax.swing.JLabel();
        lblDetail5 = new javax.swing.JLabel();
        lblAccIcon1 = new javax.swing.JLabel();
        txtPincode = new javax.swing.JTextField();
        lblAccIcon2 = new javax.swing.JLabel();
        txtNewPasswordFG = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLogin.setBackground(new java.awt.Color(28, 30, 33));
        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome back");
        pnlLogin.add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 271, -1));

        lblDetail.setFont(new java.awt.Font("Dialog", 1, 17)); // NOI18N
        lblDetail.setForeground(new java.awt.Color(204, 204, 204));
        lblDetail.setText("Join with other people in group ");
        pnlLogin.add(lblDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblAccIcon.setForeground(new java.awt.Color(118, 119, 122));
        lblAccIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_male_user_30px.png"))); // NOI18N
        lblAccIcon.setText("User name");
        pnlLogin.add(lblAccIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 40));

        txtUser.setBackground(new java.awt.Color(28, 30, 33));
        txtUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(118, 119, 122));
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(34, 37, 40)));
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
        });
        pnlLogin.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 315, 40));

        lblPassicon.setForeground(new java.awt.Color(118, 119, 122));
        lblPassicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_secure_30px.png"))); // NOI18N
        lblPassicon.setText("Password");
        pnlLogin.add(lblPassicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 40));

        txtPassword.setBackground(new java.awt.Color(28, 30, 33));
        txtPassword.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(118, 119, 122));
        txtPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(34, 37, 40)));
        txtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordFocusLost(evt);
            }
        });
        pnlLogin.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 315, 40));

        chkPassword.setBackground(new java.awt.Color(28, 30, 33));
        chkPassword.setForeground(new java.awt.Color(255, 255, 255));
        chkPassword.setText("Show Password");
        chkPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPasswordActionPerformed(evt);
            }
        });
        pnlLogin.add(chkPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 120, -1));

        lblForgot.setForeground(new java.awt.Color(255, 255, 255));
        lblForgot.setText("Forgot Password ?");
        lblForgot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgotMouseClicked(evt);
            }
        });
        pnlLogin.add(lblForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 120, -1));

        lblLine.setForeground(new java.awt.Color(145, 147, 148));
        lblLine.setText("_________________");
        pnlLogin.add(lblLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 390, 110, -1));

        btnLogin.setBackground(new java.awt.Color(82, 104, 244));
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setPreferredSize(new java.awt.Dimension(315, 40));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });

        lblLogin1.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblLogin1.setForeground(new java.awt.Color(180, 190, 250));
        lblLogin1.setText("Login");

        javax.swing.GroupLayout btnLoginLayout = new javax.swing.GroupLayout(btnLogin);
        btnLogin.setLayout(btnLoginLayout);
        btnLoginLayout.setHorizontalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnLoginLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(lblLogin1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnLoginLayout.setVerticalGroup(
            btnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 440, 310, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Don't have Account ?");
        pnlLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 510, 150, 20));

        lblSignUp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(153, 153, 255));
        lblSignUp.setText("Sign up now");
        lblSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignUpMouseClicked(evt);
            }
        });
        pnlLogin.add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 100, 20));

        lblClose.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblClose.setForeground(new java.awt.Color(255, 102, 102));
        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setText("X");
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
        });
        pnlLogin.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 40, 40));

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 380, 630));

        pnlSignup.setBackground(new java.awt.Color(28, 30, 33));
        pnlSignup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblnameIcon.setForeground(new java.awt.Color(118, 119, 122));
        lblnameIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_add_30px_1.png"))); // NOI18N
        lblnameIcon.setText("Name");
        pnlSignup.add(lblnameIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, 40));

        lblEmailIcon.setForeground(new java.awt.Color(118, 119, 122));
        lblEmailIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_mail_30px.png"))); // NOI18N
        lblEmailIcon.setText("Email");
        pnlSignup.add(lblEmailIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, 40));

        lblWelcome1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblWelcome1.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome1.setText("Sign Up");
        pnlSignup.add(lblWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 271, -1));

        lblDetail2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblDetail2.setForeground(new java.awt.Color(204, 204, 204));
        lblDetail2.setText(" Become one of us and develop your abilities");
        pnlSignup.add(lblDetail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        lblAccIconSignUp.setForeground(new java.awt.Color(118, 119, 122));
        lblAccIconSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_male_user_30px.png"))); // NOI18N
        lblAccIconSignUp.setText("User name");
        pnlSignup.add(lblAccIconSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 40));

        txtName.setBackground(new java.awt.Color(28, 30, 33));
        txtName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(118, 119, 122));
        txtName.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(34, 37, 40)));
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlSignup.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 315, 40));

        lblPassiconSignUp.setForeground(new java.awt.Color(118, 119, 122));
        lblPassiconSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_secure_30px.png"))); // NOI18N
        lblPassiconSignUp.setText("Password");
        pnlSignup.add(lblPassiconSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, 40));

        txtPasswordSignUp.setBackground(new java.awt.Color(28, 30, 33));
        txtPasswordSignUp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPasswordSignUp.setForeground(new java.awt.Color(118, 119, 122));
        txtPasswordSignUp.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(34, 37, 40)));
        txtPasswordSignUp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPasswordSignUpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPasswordSignUpFocusLost(evt);
            }
        });
        pnlSignup.add(txtPasswordSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 315, 40));

        chkPasswordSignUp.setBackground(new java.awt.Color(28, 30, 33));
        chkPasswordSignUp.setForeground(new java.awt.Color(255, 255, 255));
        chkPasswordSignUp.setText("Show Password");
        chkPasswordSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPasswordSignUpActionPerformed(evt);
            }
        });
        pnlSignup.add(chkPasswordSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 120, -1));

        btnSignUp.setBackground(new java.awt.Color(82, 104, 244));
        btnSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSignUp.setPreferredSize(new java.awt.Dimension(315, 40));
        btnSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSignUpMouseExited(evt);
            }
        });

        lblLogin2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblLogin2.setForeground(new java.awt.Color(180, 190, 250));
        lblLogin2.setText("Create Account");

        javax.swing.GroupLayout btnSignUpLayout = new javax.swing.GroupLayout(btnSignUp);
        btnSignUp.setLayout(btnSignUpLayout);
        btnSignUpLayout.setHorizontalGroup(
            btnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSignUpLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lblLogin2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSignUpLayout.setVerticalGroup(
            btnSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlSignup.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 310, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Already have Account?");
        pnlSignup.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 170, 20));

        lblSignIn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSignIn.setForeground(new java.awt.Color(153, 153, 255));
        lblSignIn.setText("Sign in now");
        lblSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignInMouseClicked(evt);
            }
        });
        pnlSignup.add(lblSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 570, 100, 20));

        lblConfirm.setForeground(new java.awt.Color(118, 119, 122));
        lblConfirm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_checked_30px_1.png"))); // NOI18N
        lblConfirm.setText("Confirm Password");
        pnlSignup.add(lblConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 40));

        txtConfirm.setBackground(new java.awt.Color(28, 30, 33));
        txtConfirm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtConfirm.setForeground(new java.awt.Color(118, 119, 122));
        txtConfirm.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(34, 37, 40)));
        txtConfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmFocusLost(evt);
            }
        });
        pnlSignup.add(txtConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 315, 40));

        txtUserSignUp1.setBackground(new java.awt.Color(28, 30, 33));
        txtUserSignUp1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtUserSignUp1.setForeground(new java.awt.Color(118, 119, 122));
        txtUserSignUp1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(34, 37, 40)));
        txtUserSignUp1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserSignUp1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserSignUp1FocusLost(evt);
            }
        });
        txtUserSignUp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserSignUp1MouseClicked(evt);
            }
        });
        txtUserSignUp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserSignUp1ActionPerformed(evt);
            }
        });
        pnlSignup.add(txtUserSignUp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 315, 40));

        cboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Manager" }));
        pnlSignup.add(cboRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        txtEmail.setBackground(new java.awt.Color(28, 30, 33));
        txtEmail.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(118, 119, 122));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(34, 37, 40)));
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmailMouseClicked(evt);
            }
        });
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        pnlSignup.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 315, 40));

        getContentPane().add(pnlSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 380, 630));

        pnlLogo.setPreferredSize(new java.awt.Dimension(570, 630));
        pnlLogo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEdusys.setFont(new java.awt.Font("Gill Sans MT", 1, 72)); // NOI18N
        lblEdusys.setForeground(new java.awt.Color(255, 255, 255));
        lblEdusys.setText("EduSys");
        pnlLogo.add(lblEdusys, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 270, 90));

        lblTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("Convenience - Security - Fast");
        pnlLogo.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        lblDecription.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDecription.setForeground(new java.awt.Color(204, 204, 204));
        lblDecription.setText("Education Management Program");
        pnlLogo.add(lblDecription, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        lblCity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCity.setForeground(new java.awt.Color(255, 255, 255));
        lblCity.setText("</>LapTrinhCity");
        pnlLogo.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblContact.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblContact.setForeground(new java.awt.Color(204, 204, 204));
        lblContact.setText("Contact: facebook.com/sang.vinh.52035");
        pnlLogo.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, -1, -1));

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginform2.png"))); // NOI18N
        pnlLogo.add(lblImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(pnlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlForgot.setBackground(new java.awt.Color(28, 30, 33));
        pnlForgot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcome2.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lblWelcome2.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome2.setText("Forgot Your Password?");
        pnlForgot.add(lblWelcome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 350, -1));

        lblDetail3.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblDetail3.setForeground(new java.awt.Color(204, 204, 204));
        lblDetail3.setText("3.Create new password");
        pnlForgot.add(lblDetail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        btnChangePasswordFG.setBackground(new java.awt.Color(82, 104, 244));
        btnChangePasswordFG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChangePasswordFG.setPreferredSize(new java.awt.Dimension(315, 40));
        btnChangePasswordFG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnChangePasswordFGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChangePasswordFGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangePasswordFGMouseExited(evt);
            }
        });

        lblLogin3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        lblLogin3.setForeground(new java.awt.Color(180, 190, 250));
        lblLogin3.setText("CHANGE PASSWORD");

        javax.swing.GroupLayout btnChangePasswordFGLayout = new javax.swing.GroupLayout(btnChangePasswordFG);
        btnChangePasswordFG.setLayout(btnChangePasswordFGLayout);
        btnChangePasswordFGLayout.setHorizontalGroup(
            btnChangePasswordFGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnChangePasswordFGLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblLogin3)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        btnChangePasswordFGLayout.setVerticalGroup(
            btnChangePasswordFGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogin3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        pnlForgot.add(btnChangePasswordFG, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 310, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Have you change your password?");
        pnlForgot.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 240, 20));

        lblSignIn1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSignIn1.setForeground(new java.awt.Color(153, 153, 255));
        lblSignIn1.setText("Sign in now");
        lblSignIn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignIn1MouseClicked(evt);
            }
        });
        pnlForgot.add(lblSignIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, 100, 20));

        lblDetail4.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblDetail4.setForeground(new java.awt.Color(204, 204, 204));
        lblDetail4.setText("1. Check your Email box");
        pnlForgot.add(lblDetail4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblDetail5.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        lblDetail5.setForeground(new java.awt.Color(204, 204, 204));
        lblDetail5.setText("2.enter the pin code included in the mail");
        pnlForgot.add(lblDetail5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lblAccIcon1.setForeground(new java.awt.Color(118, 119, 122));
        lblAccIcon1.setText("PIN CODE:");
        pnlForgot.add(lblAccIcon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 40));

        txtPincode.setBackground(new java.awt.Color(28, 30, 33));
        txtPincode.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPincode.setForeground(new java.awt.Color(118, 119, 122));
        txtPincode.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(34, 37, 40)));
        txtPincode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPincodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPincodeFocusLost(evt);
            }
        });
        txtPincode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPincodeMouseClicked(evt);
            }
        });
        pnlForgot.add(txtPincode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 250, 40));

        lblAccIcon2.setForeground(new java.awt.Color(118, 119, 122));
        lblAccIcon2.setText("Your New Password:");
        pnlForgot.add(lblAccIcon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 40));

        txtNewPasswordFG.setBackground(new java.awt.Color(28, 30, 33));
        txtNewPasswordFG.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtNewPasswordFG.setForeground(new java.awt.Color(118, 119, 122));
        txtNewPasswordFG.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(34, 37, 40)));
        txtNewPasswordFG.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewPasswordFGFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewPasswordFGFocusLost(evt);
            }
        });
        txtNewPasswordFG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNewPasswordFGMouseClicked(evt);
            }
        });
        pnlForgot.add(txtNewPasswordFG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 320, 40));

        getContentPane().add(pnlForgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 380, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtUserMouseClicked

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
        SelectTextField(txtUser,lblAccIcon);
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        // TODO add your handling code here:
        ExitTextField(txtUser,lblAccIcon);
    }//GEN-LAST:event_txtUserFocusLost

    private void txtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusGained
        // TODO add your handling code here:
        SelectTextField(txtPassword,lblPassicon);
    }//GEN-LAST:event_txtPasswordFocusGained

    private void txtPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordFocusLost
        // TODO add your handling code here:
        ExitTextField(txtPassword,lblPassicon);
    }//GEN-LAST:event_txtPasswordFocusLost

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(105, 124, 242));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        btnLogin.setBackground(new Color(82,104,244));
    }//GEN-LAST:event_btnLoginMouseExited

    private void chkPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPasswordActionPerformed
        // TODO add your handling code here:
        if (chkPassword.isSelected()) {
            txtPassword.setEchoChar((char)0); //password = JPasswordField
        } else {
           txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_chkPasswordActionPerformed

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        // TODO add your handling code here:
        SelectTextField(txtName, lblnameIcon);
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        // TODO add your handling code here:
        ExitTextField(txtName, lblnameIcon);
    }//GEN-LAST:event_txtNameFocusLost

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNameMouseClicked

    private void txtPasswordSignUpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordSignUpFocusGained
        // TODO add your handling code here:
        SelectTextField(txtPasswordSignUp, lblPassiconSignUp);
    }//GEN-LAST:event_txtPasswordSignUpFocusGained

    private void txtPasswordSignUpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPasswordSignUpFocusLost
        // TODO add your handling code here:
        ExitTextField(txtPasswordSignUp, lblPassiconSignUp);
    }//GEN-LAST:event_txtPasswordSignUpFocusLost

    private void chkPasswordSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPasswordSignUpActionPerformed
        // TODO add your handling code here:
         if (chkPasswordSignUp.isSelected()) {
            txtPasswordSignUp.setEchoChar((char)0); //password = JPasswordField
        } else {
           txtPasswordSignUp.setEchoChar('*');
        }
    }//GEN-LAST:event_chkPasswordSignUpActionPerformed

    private void btnSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseEntered
        // TODO add your handling code here:
         btnSignUp.setBackground(new Color(105, 124, 242));
    }//GEN-LAST:event_btnSignUpMouseEntered

    private void btnSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseExited
        // TODO add your handling code here:
        btnSignUp.setBackground(new Color(82,104,244));
    }//GEN-LAST:event_btnSignUpMouseExited

    private void txtConfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmFocusGained
        // TODO add your handling code here:
        SelectTextField(txtConfirm, lblConfirm);
    }//GEN-LAST:event_txtConfirmFocusGained

    private void txtConfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmFocusLost
        // TODO add your handling code here:
        ExitTextField(txtConfirm, lblConfirm);
    }//GEN-LAST:event_txtConfirmFocusLost

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void lblSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignInMouseClicked
        // TODO add your handling code here:
        pnlSignup.setVisible(false);
        pnlLogin.setVisible(true);
        pnlForgot.setVisible(false);
    }//GEN-LAST:event_lblSignInMouseClicked

    private void lblSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseClicked
        // TODO add your handling code here:
        pnlSignup.setVisible(true);
        pnlLogin.setVisible(false);
        pnlForgot.setVisible(false);
    }//GEN-LAST:event_lblSignUpMouseClicked

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignUpMouseClicked
        // TODO add your handling code here:
        signUp();
    }//GEN-LAST:event_btnSignUpMouseClicked

    private void txtUserSignUp1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserSignUp1FocusGained
        // TODO add your handling code here:
        SelectTextField(txtUserSignUp1, lblAccIconSignUp);
    }//GEN-LAST:event_txtUserSignUp1FocusGained

    private void txtUserSignUp1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserSignUp1FocusLost
        // TODO add your handling code here:
        ExitTextField(txtUserSignUp1, lblAccIconSignUp);
    }//GEN-LAST:event_txtUserSignUp1FocusLost

    private void txtUserSignUp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserSignUp1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserSignUp1MouseClicked

    private void txtUserSignUp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserSignUp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserSignUp1ActionPerformed

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        // TODO add your handling code here:
        end();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        // TODO add your handling code here:
        SelectTextField(txtEmail, lblEmailIcon);
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        // TODO add your handling code here:
        ExitTextField(txtEmail, lblEmailIcon);
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnChangePasswordFGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePasswordFGMouseClicked
        // TODO add your handling code here:
        changePasswordFG();
    }//GEN-LAST:event_btnChangePasswordFGMouseClicked

    private void btnChangePasswordFGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePasswordFGMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePasswordFGMouseEntered

    private void btnChangePasswordFGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePasswordFGMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnChangePasswordFGMouseExited

    private void lblSignIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignIn1MouseClicked
        // TODO add your handling code here:
        lblSignInMouseClicked(null);
    }//GEN-LAST:event_lblSignIn1MouseClicked

    private void txtPincodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPincodeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPincodeFocusGained

    private void txtPincodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPincodeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPincodeFocusLost

    private void txtPincodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPincodeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPincodeMouseClicked

    private void lblForgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgotMouseClicked
        // TODO add your handling code here:
        
        forgotPassword();
    }//GEN-LAST:event_lblForgotMouseClicked

    private void txtNewPasswordFGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewPasswordFGMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordFGMouseClicked

    private void txtNewPasswordFGFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPasswordFGFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordFGFocusLost

    private void txtNewPasswordFGFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewPasswordFGFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewPasswordFGFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnChangePasswordFG;
    private javax.swing.JPanel btnLogin;
    private javax.swing.JPanel btnSignUp;
    private javax.swing.JComboBox<String> cboRole;
    private javax.swing.JCheckBox chkPassword;
    private javax.swing.JCheckBox chkPasswordSignUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAccIcon;
    private javax.swing.JLabel lblAccIcon1;
    private javax.swing.JLabel lblAccIcon2;
    private javax.swing.JLabel lblAccIconSignUp;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblConfirm;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDecription;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblDetail2;
    private javax.swing.JLabel lblDetail3;
    private javax.swing.JLabel lblDetail4;
    private javax.swing.JLabel lblDetail5;
    private javax.swing.JLabel lblEdusys;
    private javax.swing.JLabel lblEmailIcon;
    private javax.swing.JLabel lblForgot;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblLine;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblLogin2;
    private javax.swing.JLabel lblLogin3;
    private javax.swing.JLabel lblPassicon;
    private javax.swing.JLabel lblPassiconSignUp;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JLabel lblSignIn1;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JLabel lblWelcome1;
    private javax.swing.JLabel lblWelcome2;
    private javax.swing.JLabel lblnameIcon;
    private javax.swing.JPanel pnlForgot;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlSignup;
    private javax.swing.JPasswordField txtConfirm;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNewPasswordFG;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordSignUp;
    private javax.swing.JTextField txtPincode;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtUserSignUp1;
    // End of variables declaration//GEN-END:variables

    private void prepareUI() {
        pnlSignup.setVisible(false);
        pnlForgot.setVisible(false);
        addComponentListener(new ComponentAdapter() {
               @Override
                public void componentResized(ComponentEvent e) {
                    setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 25, 25));
                    
                }
            });
        
    }
    
    private void SelectTextField(JTextField txtForm, JLabel lblIcon) {
        lblIcon.setVisible(false);
        txtForm.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(50, 60, 116)));
        txtForm.setBackground(new Color(37,39,42));
    }
    private void ExitTextField(JTextField txtForm, JLabel lblIcon) {
        if(txtForm.getText().equals(""))
            lblIcon.setVisible(true);
        else 
            lblIcon.setVisible(false);
        txtForm.setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, new Color(34,37,40)));
        txtForm.setBackground(new Color(28,30,33));
    }

    private void login() {
        try {
            String user = txtUser.getText();
            String pass = txtPassword.getText();
            Staff staff = dao.selectByID(user);
            
            if(staff==null) {
                JOptionPane.showMessageDialog(this, "Staff not exist !!!");
            } else if (!pass.equals(staff.getStaffPassword())) {
                JOptionPane.showMessageDialog(this, "Wrongs password");
            } else {
                Auth.user = staff;
                new Main().setVisible(true);
                this.dispose();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void signUp() {
        String user = txtUserSignUp1.getText();
        String pass = txtPasswordSignUp.getText();
        String confirm = txtConfirm.getText();
        String email = txtEmail.getText();
        String name = txtName.getText();
        Boolean role = cboRole.getSelectedItem().equals("Staff");
        // check if the Staff already exists
        Staff staff = dao.selectByID(user);
        try {
            validateInfor();
            
            if(staff!=null) 
                JOptionPane.showMessageDialog(this, "UserID already exist !!");
            if(!pass.equals(confirm)) 
                JOptionPane.showMessageDialog(this, "two passwords did not match !!");
            else {
                Staff newStaff = new Staff();
                newStaff.setStaffID(user);
                newStaff.setStaffPassword(pass);
                newStaff.setStaffRole(role);
                newStaff.setStaffName(name);
                newStaff.setStaffEmail(email);
                dao.insert(newStaff);
                MsgBox.alert(this, "Your account has been created");
            }
            
        } catch(Exception ex) {
            throw new RuntimeException(ex);
        }
    }
    
    private void end() {
        System.exit(0);
    }

    private void validateInfor() {
        String user = txtUserSignUp1.getText();
        String pass = txtPasswordSignUp.getText();
        String confirm = txtConfirm.getText();
        String email = txtEmail.getText();
        String name = txtName.getText();
        if(user.length()<6) {
            JOptionPane.showMessageDialog(this, "username length must be longer than 6");
            return;
        } else if(pass.length()<6) {
            JOptionPane.showMessageDialog(this, "password length must be longer than 6");
            return;
        } else if(!email.matches("\\w+@\\w+(\\.\\w+){1,2}")) {
            JOptionPane.showMessageDialog(this, "Email invalid");
            return;
        } else if(name.length()<6) {
            JOptionPane.showMessageDialog(this, "Name length must be longer than 6");
            return;
        }
    }
    private String randomString() {
        int leftLimit = 97; // letter 'a'
        int rightLimit = 122; // letter 'z'
        int targetStringLength = 10;
        Random random = new Random();
        StringBuilder buffer = new StringBuilder(targetStringLength);
        for (int i = 0; i < targetStringLength; i++) {
            int randomLimitedInt = leftLimit + (int) 
              (random.nextFloat() * (rightLimit - leftLimit + 1));
            buffer.append((char) randomLimitedInt);
        }
        String generatedString = buffer.toString();
        
        System.out.println(generatedString);
        return generatedString;
    }
    
    Staff validStaff;
    String random = "";
    private void forgotPassword() {
        String user = txtUser.getText();
        this.validStaff = dao.selectByID(user);
        
        if(user.length()==0) {
            MsgBox.alert(this,"You must enter user name to change your password");
            return ;
        } else if(validStaff == null) {
            MsgBox.alert(this, "User name not exist");
            return ;
        }
        else {
            pnlLogin.setVisible(false);
            pnlSignup.setVisible(false);
            pnlForgot.setVisible(true);
            
            this.random = randomString();
            Xmail x = new Xmail();
            Thread t = new Thread(){
                @Override
                public void run() {
                    x.sendMail(validStaff.getStaffEmail(), "Your PIN Code", "Your PIN code is: " + random);
                }
            };
            t.start();
            
            
            
            
        }
        
    }
    private void changePasswordFG() {
        if(!txtPincode.getText().equals(this.random)) 
            MsgBox.alert(this, "Wrong PIN CODE");
        else if(txtNewPasswordFG.getText().length()<6) {
            MsgBox.alert(this, "Password length must >= 6");
        }
        else {
            changePassword(validStaff, txtNewPasswordFG.getText());
            MsgBox.alert(this, "Change Password Successfully");
        }
    }
    
    private void changePassword(Staff staff, String pw) {
        staff.setStaffPassword(pw);
        dao.update(staff);
        MsgBox.alert(this, "Change Password Successfully");
    }

    

    
    
    

    
}
